### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by SamueleBumbaca** [ArduCAM/RPI_Motorized_IRCut_Control#6]
Problem during execution after installing on Raspberry Pi 3b
 `sudo ./CameraLED.py state
Traceback (most recent call last):
  File "./CameraLED.py", line 65, in <module>
    print("State: " + str(led.state()))
  File "./CameraLED.py", line 53, in state
    return self.__firmware_request__(self.GET_TAG)
  File "./CameraLED.py", line 31, in __firmware_request__
    result = fcntl.ioctl(self.__vcio, self.IOCTL_MAILBOX, buffer)
OSError: [Errno 22] Invalid argument`
Tried to build from source the cpp version after building wiringpi:
`./irCut 1
The hardware version =  a020d4
Segmentation fault
...@raspberrypi3B:~/RPI_Motorized_IRCut_Control/camIrCutControl $ ./irCut 1
The hardware version =  a020d4
Segmentation fault
...@raspberrypi3B:~/RPI_Motorized_IRCut_Control/camIrCutControl $ ./irCut 0
The hardware version =  a020d4
Segmentation fault`

**Comment by billydanke** [comment]
I know this is years later, but it's more than likely to do with 32-bit vs 64-bit architecture. If you're running a 64-bit version of Pi OS, try changing the IOCTL_MAILBOX = 0xC0086400 instead
